services:
  - type: web
    name: kodey-ai-streamlit
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      chmod +x start.sh
      ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false 