[theme]
primaryColor = "#1E90FF"  # Dodger Blue
backgroundColor = "#121212"  # Dark background
secondaryBackgroundColor = "#1E1E1E"  # Slightly lighter for contrast
textColor = "#FFFFFF"  # White text
font = "sans serif" 